### PR TITLE
Add upgrade support for Multicluster Engine, for development (workaround)

### PR DESCRIPTION
**Pull request by jnpacker**
**Description of the change:**
1. Include a script that has interactive and automatic run modes
2. Include a --watch to see the change occur
3. Update the readme. State this is for development!

Signed-off-by: Joshua Packer <jpacker@redhat.com>

**Motivation for the change:**
I didn't want to start fresh every time I make a commit.

### CODE REVIEW

**Comment by jnpacker** [comment]
/cc @JakobGray 

I suspect there is a field on the mce resource I can watch to make sure it gets full configured with the new images?
1. Watch the mce operator
2. Watch the mce resource to see that it completes??  

This can be part two.

**Comment by jnpacker** [comment]
@gurnben @Kyl-Bempah @tpouyer looking for an approve

**Review by gurnben — APPROVED** [review]
LGTM

**Pull request merged**
