### PR TITLE
add mce status

### PR DESCRIPTION
**Pull request by cameronmwall**
Signed-off-by: Cameron Wall <cwall@redhat.com>

**Description of the change:**
added more verbose status for the MCE subcomponents

**Motivation for the change:**
help with the ease of debugging

### CODE REVIEW

**Review by JakobGray — COMMENTED** [review]
Can the deploy repo still install 2.4 and earlier versions with this change? I see further up in the script the MCE installation is conditional on the version being installed https://github.com/stolostron/deploy/blob/659bff6396468257e80340681273f6cec44ba08c/start.sh#L235

**Review by gurnben — APPROVED** [review]
LGTM!

**Comment by gurnben** [comment]
Good catch @JakobGray  - @cameronmwall can we conditionalize this on version (2.5 and up specifically) like Jakob linked?

**Comment by cameronmwall** [comment]
@gurnben @JakobGray thanks for the catch guys. I repeated the conditional used above in my logic

**Comment by gurnben** [comment]
LGTM!

**Review by gurnben — APPROVED** [review]
LGTM!

**Pull request merged**
